import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import TailHeader from "@/components/Layouts/Header/TailHeader";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko">
      <body className={inter.className}>
        <TailHeader />
        <div className="mx-auto max-w-7xl px-2 sm:px-6 lg:px-8">{children}</div>
      </body>
    </html>
  );
}
